openapi: 3.0.0
info:
  version: 1.0.0
  title: A
  description: A
paths: {}
components:
  schemas:
    Body_post_medias_api_medias__post:
      properties:
        file:
          type: string
          format: binary
          title: File
      type: object
      required:
        - file
      title: Body_post_medias_api_medias__post
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Like:
      properties:
        user_id:
          type: integer
          title: ID User
        name:
          type: string
          title: Name User
      type: object
      required:
        - user_id
        - name
      title: Like
    MediaOut:
      properties:
        rusult:
          type: boolean
          title: Response status
        media_id:
          type: integer
          title: Media ID
      type: object
      required:
        - rusult
        - media_id
      title: MediaOut
    ResultClass:
      properties:
        rusult:
          type: boolean
          title: Response status
      type: object
      required:
        - rusult
      title: ResultClass
    Tweet:
      properties:
        id:
          type: integer
          title: ID Tweet
        content:
          type: string
          title: Text Tweet
        attachments:
          items:
            type: string
          type: array
          title: Links of media files
        author:
          allOf:
            - $ref: '#/components/schemas/User'
          title: Info about author
        likes:
          items:
            $ref: '#/components/schemas/Like'
          type: array
          title: Info about authors of the likes
      type: object
      required:
        - id
        - content
        - attachments
        - author
        - likes
      title: Tweet
    TweetIn:
      properties:
        tweet_data:
          type: string
          title: Text Tweet
        tweet_media_ids:
          items:
            type: integer
          type: array
          title: ID medias of Tweet
      type: object
      required:
        - tweet_data
        - tweet_media_ids
      title: TweetIn
    TweetOut:
      properties:
        rusult:
          type: boolean
          title: Response status
        tweet_id:
          type: integer
          title: Tweet ID
      type: object
      required:
        - rusult
        - tweet_id
      title: TweetOut
    Tweets:
      properties:
        rusult:
          type: boolean
          title: Response status
        tweets:
          items:
            $ref: '#/components/schemas/Tweet'
          type: array
          title: List of Tweets
      type: object
      required:
        - rusult
        - tweets
      title: Tweets
    User:
      properties:
        id:
          type: integer
          title: ID User
        name:
          type: string
          title: Name User
      type: object
      required:
        - id
        - name
      title: User
    UserAll:
      properties:
        id:
          type: integer
          title: ID User
        name:
          type: string
          title: Name User
        followers:
          items:
            $ref: '#/components/schemas/User'
          type: array
          title: User Followers
        following:
          items:
            $ref: '#/components/schemas/User'
          type: array
          title: User Following
      type: object
      required:
        - id
        - name
        - followers
        - following
      title: UserAll
    UserOut:
      properties:
        rusult:
          type: boolean
          title: Response status
        user:
          allOf:
            - $ref: '#/components/schemas/UserAll'
          title: User info
      type: object
      required:
        - rusult
        - user
      title: UserOut
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError